### ISSUE TITLE
Can't make Single File Components i18n translations to work in Storybook

### ISSUE THREAD

**Issue by dlucian** [dlucian/vuejs-storybook-i18n#1]
SFC translations don't seem to go well with Storybook, as I can't get storybook's webpack configuration to load the SFC translations. 

There's a i18n component called HelloI18n, that works just fine when running the Vue app with

```shell
$ yarn serve
```

<img width="1210" alt="Screen Shot 2019-06-06 at 10 10 54" src="https://user-images.githubusercontent.com/1525121/59014176-a9d56900-8844-11e9-900b-f7126bcaab14.png">

However, when running storybook:

```shell
$ yarn storybook
```

Only the generic translation file is loaded (`src/locales/en.js`): 

<img width="1213" alt="Screen Shot 2019-06-06 at 10 13 14" src="https://user-images.githubusercontent.com/1525121/59014219-c5407400-8844-11e9-8186-37907087c62c.png">

I have tried adding a custom `.storybook/webpack.config.js` with:

```javascript
const path = require('path');

// Export a function. Accept the base config as the only param.
module.exports = async ({ config, mode }) => {
  // `mode` has a value of 'DEVELOPMENT' or 'PRODUCTION'
  // You can change the configuration based on that.
  // 'PRODUCTION' is used when building the static version of storybook.
  
  // Make whatever fine-grained changes you need
  config.module.rules.push({
    resourceQuery: /blockType=i18n/,
    type: 'javascript/auto',
    loader: '@kazupon/vue-i18n-loader',
  });

  // Return the altered config
  return config;
};
```

But still no luck. I just can't get storybook to load the single-file-component translations from `.vue` files. 

Any ideas?

Resources:

 * https://github.com/kazupon/vue-i18n-loader
 * https://kazupon.github.io/vue-i18n/
 * https://github.com/mattrothenberg/vue-storybook-example-project/blob/master/vue.config.js
 * https://kazupon.github.io/vue-i18n/guide/sfc.html#webpack
 * https://github.com/storybookjs/storybook/issues/1573#issuecomment-498986787
 * https://github.com/mattrothenberg/vue-storybook-example-project/blob/master/vue.config.js
 * https://github.com/kazupon/vue-i18n/blob/dev/examples/storybook/src/stories/index.js

**Comment by goblindaydream** [comment]
I sent an email to dlucian@gmail.com. I fixed i18n issue already and need to get permission to push.

**Comment by dlucian** [comment]
Issue not yet fixed. Anyone? 🌞

**Comment by graup** [comment]
Isn't the problem that we should add i18n to the $root to enable the fallbacks? There doesn't seem to be an easy way to do that. https://github.com/storybookjs/storybook/issues/6548

**Comment by graup** [comment]
I found a solution by just manually assigning the root variable. I also use the contexts addon. Looks something like this

```js
import { withContexts } from '@storybook/addon-contexts/vue';

const localeContext = {
  name: 'I18NProvider',
  props: ['locale'],
  watch: {
    locale: function(newValue) {
      this.$root.$i18n.locale = newValue;
    }
  },
  i18n,
  beforeCreate: function() {
    this.$root._i18n = this.$i18n;
  },
  template: '<div><slot /></div>',
};
const topLevelContexts = [
  {
    icon: 'globe',
    title: 'Locale',
    components: [localeContext],
    params: [
      {
        name: 'English',
        props: {
          locale: 'en'
        },
        default: true,
      },
      {
        name: 'Korean',
        props: {
          locale: 'ko'
        },
      },
    ],
  },
];
addDecorator(withContexts(topLevelContexts));
```

**Comment by dlucian** [comment]
> Isn't the problem that we should add i18n to the $root to enable the fallbacks? There doesn't seem to be an easy way to do that. [storybookjs/storybook#6548](https://github.com/storybookjs/storybook/issues/6548)

Not really sure how the $root i18n is linked to the SFC translations. I was under the impression that it's a loader issue, not being able to convince the storybook loader to parse and properly use SFC translations.

**Comment by crusenov** [comment]
@graup  With this i18n configuration that you provided addReadme addon doesn't update. Any idea?
I think the problem is in template section, because if I comment `template: '<div><slot /></div>'` everything is ok except the localization.

**Comment by dlucian** [comment]
@graup @crusenov The most frustrating thing is that I don't understand why all this doesn't work. It's just trial and error, without understanding the root cause of this.

**Comment by dlucian** [comment]
The solution provided by @graup seems to be the only workaround at this point: https://github.com/storybookjs/storybook/issues/6548#issuecomment-504336665

**Comment by rdhainaut** [comment]
The workaround doesn t work for me.  

Do you have other idea for the i18n in SFC ? (it s so frustrating to have a storybook, stories and any translations)

**Comment by dlucian** [comment]
@rdhainaut it should work, here's my actual code in storybook's `config.js`:

```javascript
import i18n from '../src/plugins/i18n';

addDecorator(() => ({
  vuetify: vuetifyConfig,
  i18n,
  router,
  beforeCreate: function() {
    this.$root._i18n = this.$i18n;
  },
  template: '<v-app><v-content><story/></v-content></v-app>',
}));
```

And the i18n.js file:

```javascript
import Vue from 'vue';
import VueI18n from 'vue-i18n';
import messages from '@/lang/messages';

Vue.use(VueI18n);

const getLocale = () => {
    return (window.navigator.userLanguage || window.navigator.language).substring(0, 2);
};

export default new VueI18n({
    locale: getLocale(),
    fallbackLocale: 'en',
    silentTranslationWarn: true,
    messages,
});
```

In the actual stories I don't need to add/change anything, it just works.

**Comment by rdhainaut** [comment]
I have clone your repo, try these new lines just above but with no success for SFC message
Maybe i have miss something

This is the result: 
- SFC message: hello => display the key and not the message
- locales message: hello i18n translated in src/locales/en.json !! => display the message value o/ 
![image](https://user-images.githubusercontent.com/19733832/74765280-8bed4e80-5283-11ea-819a-39816addd99c.png)

sorry to ask that but can you update this repo ?

Edit: It works ! 
I have retry in my project and it works now (i have both locales messages and SFC messages yeah) o/
Thanks for the comment, i don t know why i have missed the first time.

This is my final code
```ts
// preview.js (located at storybook config directory)
// Internationalization
import i18n from "@/i18n";

// Internationalisation
addDecorator(() => ({
  i18n,
  beforeCreate: function() {
    this.$root._i18n = this.$i18n;
  },
  template: "<story/>"
}));
```
```ts
// i18n/index.ts
import Vue from "vue";
// Vue plugins - Internationalization
import VueI18n from "vue-i18n";
import messages from "./messages.json";

// See https://kazupon.github.io/vue-i18n/started.html
Vue.use(VueI18n);

export default new VueI18n({
  fallbackLocale: "en",
  fallbackRoot: true,
  locale: "en",
  silentTranslationWarn: process.env.NODE_ENV === "production",
  silentFallbackWarn: true, // process.env.NODE_ENV === "production" // See issue: https://github.com/kazupon/vue-i18n/issues/689,
  messages: messages
});
```

```
// messages.json
{
  "en": {
    "hi": "hello world!"
  },
  "fr":{
    "hi": "bonjour tout le monde !"
  }
}
```

Et voilà ! :)

**Comment by cheesytim** [comment]
@rdhainaut thx! but, how can I change lang? using native toolbar https://storybook.js.org/docs/vue/essentials/toolbars-and-globals#advanced-usage, I've tried watch for global locale variable in decorator, but it doesn't work
